#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

NOCOLOR='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'

echo "${ORANGE}PHP-CS-Fixer start${NOCOLOR}"

PHP_CS_FIXER="vendor/friendsofphp/php-cs-fixer/php-cs-fixer"
PHP_CS_CONFIG=".php-cs-fixer.php"
CHANGED_PHP_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

if [ -n "$CHANGED_PHP_FILES" ]; then
    $PHP_CS_FIXER fix --config "$PHP_CS_CONFIG" $CHANGED_PHP_FILES;
    git add $CHANGED_PHP_FILES;
fi

echo "${GREEN}PHP-CS-Fixer finish${NOCOLOR}"

echo "${ORANGE}ESLINT start${NOCOLOR}"

ESLINT_CONFIG=".eslintrc.json"
CHANGED_JS_FILES=$(git diff --cached --name-only --diff-filter=ACM -- *.vue *.js)

if [ -n "$CHANGED_JS_FILES" ]; then
    npx eslint --fix --config "$ESLINT_CONFIG" $CHANGED_JS_FILES;
    git add $CHANGED_JS_FILES;
fi

echo "${GREEN}ESLINT finish${NOCOLOR}"
